#!/bin/sh -e

patch -p1 < no-intltool.patch

sed -i '/GETTEXT/d' gtkspell/gtkspell.c
sed -i 's/_(/(/g'   gtkspell/gtkspell.c

./configure \
    --prefix=/usr \
    --disable-nls \
    --disable-static

printf 'all:\n\ttrue\ninstall:\n\ttrue\nclean:\n\ttrue\n' > po/Makefile

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/gtk-doc"
