#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dtls_check=false \
    -Dintrospection=enabled \
    -Dvapi=enabled \
    . output

ninja -C output
ninja -C output install
