#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-static \
    --enable-mbim-qmux \
    --enable-qrtr \
    --enable-more-warnings=yes

make
make DESTDIR="$1" install
