liberapay: eudaldgr
custom: ["https://paypal.me/eudaldgr", "https://blockstream.info/address/bc1qnutxs8s6q0ssp20urdt2u9zz78lzf06s3tsymc", "https://etherscan.io/address/0xcc8D695488a45CEf5b149e084b2e2d3B91AddC2C"]
