#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddocs=false \
    -Dinstalled_tests=false \
    -Dtests=false \
    -Dbluez_backend=false \
    . output

ninja -C output
ninja -C output install
