#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dprofiling=false \
    -Dstatic=false \
    -Dexamples=false \
    -Dgtk-doc=false \
    -Dtests=false \
    . output

ninja -C output
ninja -C output install
