#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 65ff089b7f346f3809e9e0050ea32ac003465ede.patch

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dprofiling=false \
    -Dstatic=false \
    -Dexamples=false \
    -Dgtk-doc=false \
    -Dtests=false \
    . output

ninja -C output
ninja -C output install
