#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

# disable test subdirs, causes looping on builders and we don't run
# tests anyway
sed -e '/subdir/d' -i cogl/tests/meson.build

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib/mutter \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dtests=false \
    -Degl_device=true \
    -Dudev=true \
    -Dnative_backend=true \
    -Dintrospection=true \
    -Dwayland=false \
    -Dlibwacom=false \
    -Dremote_desktop=false \
    -Dprofiler=false \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/share/man"
