#!/bin/sh -e

case $TYPE in
    pre-build)
        case $PKG in
            atk)
                sed -i "s/-Dintrospection=false/-Dintrospection=true/g"       "$repo_dir/build"
            ;;
            gdk-pixbuf)
                sed -i "s/-Dgir=false/-Dgir=true/g"                           "$repo_dir/build"
            ;;
            gtk+3)
                sed -i "s/-introspection=no/-introspection=yes/g"             "$repo_dir/build"
            ;;
            pango)
                sed -i "s/-Dintrospection=disabled/-Dintrospection=enabled/g" "$repo_dir/build"
                sed -i "s/-Dgir=false/-Dgir=true/g"                           "$repo_dir/build"
            ;;
            qt5)
                sed -i "s/-no-dbus/-dbus-linked/g"                            "$repo_dir/build"
            ;;
        esac
    ;;
    post-build)
        case $PKG in
            atk)
                sed -i "s/-Dintrospection=true/-Dintrospection=false/g"       "$repo_dir/build"
            ;;
            gdk-pixbuf)
                sed -i "s/-Dgir=true/-Dgir=false/g"                           "$repo_dir/build"
            ;;
            gtk+3)
                sed -i "s/-introspection=yes/-introspection=no/g"             "$repo_dir/build"
            ;;
            pango)
                sed -i "s/-Dintrospection=enabled/-Dintrospection=disabled/g" "$repo_dir/build"
                sed -i "s/-Dgir=true/-Dgir=false/g"                           "$repo_dir/build"
            ;;
            qt5)
                sed -i "s/-dbus-linked/-no-dbus/g"                            "$repo_dir/build"
            ;;
        esac
    ;;
esac
