#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

meson \
    --prefix=/usr \
    -Dwith-zeitgeist=true \
    . output

ninja -C output
ninja -C output install
