#!/bin/sh -e

sed -i "s|@@VERSION@@|$2|" -i *.pc

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

{
    cd libraries/liblmdb 

    make CFLAGS+="-fPIC"
    make DESTDIR="$1" prefix=/usr install

    cd -
}

install -Dm0644 *.pc -t "$1/usr/lib/pkgconfig"

# Remove unused stuff
rm -rf "$1/usr/share"
