#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-python-bindings \
    --with-python-binary=python3 \
    --enable-pam \
    --with-securedir=/usr/lib/security

make
make DESTDIR="$1" install
