#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--buildtype=plain \
    -Ddocs=false \
    . output

ninja -C output
ninja -C output install
