#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < 00-musl.patch
sed -i 's/time_t/int64/g' src/Widgets/calendar/Util.vala

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
