#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --buildtype=plain \
    -Dlibgeoclue=true \
    -Ddbus-srv-user=geoclue \
    -Ddbus-sys-dir=/usr/share/dbus-1/system.d \
    -Ddemo-agent=false \
    -Dgtk-doc=false \
    -Dnmea-source=false \
    -Dintrospection=true \
    -D3g-source=false \
    -Dcdma-source=false \
    -Dmodem-gps-source=false \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/lib/geoclue-2.0"
rm -rf "$1/usr/share/man"
