#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --with-polkit=permissive \
    --disable-gtk-doc \
    --disable-static \
    --with-dbus-sys-dir=/etc/dbus-1/system.d \
    --enable-vala=yes

make
make DESTDIR="$1" install

install -Dm755 modemmanager.run "$1/etc/sv/modemmanager/run"
