#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-base-dir=/usr/lib/udev \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-polkit=permissive \
    --disable-gtk-doc \
    --disable-static \
    --with-dbus-sys-dir=/etc/dbus-1/system.d \
    --enable-vala=yes

make
make DESTDIR="$1" install

# Remove unused stuff
rm -rf "$1/usr/share/man"
rm -rf "$1/usr/share/locale"
rm -rf "$1/usr/share/dbus-1/system-services"

install -Dm644 modemmanager.rules "$1/usr/share/polkit-1/rules.d/01-org.freedesktop.ModemManager.rules"
install -Dm755 modemmanager.run   "$1/etc/sv/modemmanager/run"
