#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-static \
    --enable-introspection=yes

make
make DESTDIR="$1" install

# Remove unused stuff
rm -rf "$1/usr/share/man"
rm -rf "$1/usr/share/gtk-doc"
