#!/bin/sh -e

export DESTDIR="$1"

# Next release will come with libhandy-1, remove this
sed -i "s/libhandy-0.0/libhandy-1', version: '>= 0.80.0/g" meson.build
sed -i "s/Paginator/Carousel/g" src/MainWindow.vala
sed -i "s/Paginator/Carousel/g" src/PageChecker.vala
sed -i "s/Paginator/Carousel/g" src/Switcher.vala
sed -i "s/paginator/carousel/g" src/MainWindow.vala
sed -i "s/paginator/carousel/g" src/PageChecker.vala
sed -i "s/paginator/carousel/g" src/Switcher.vala

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
