#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=plain \
    -Dtrust_paths=/etc/ssl/certs/ca-certificates.crt \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
# shellcheck disable=2115
rm -rf "$1/etc"
# shellcheck disable=2115
rm -rf "$1/usr/bin"
rm -rf "$1/usr/libexec"
