#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < vapilink.patch

meson \
    --prefix=/usr \
    --buildtype=plain \
    -Dintrospection=true \
    -Dssh=false \
    -Dpython=false \
    -Dvapi=true \
    -Dgtk_doc=false \
    . output

ninja -C output
ninja -C output install
