#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=plain \
    --sysconfdir=/etc \
    -Denable-installed-tests=false \
    -Denable-gtk-doc=false \
    build

ninja -C build
ninja -C build install
