#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib/gnome-settings-daemon \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dsystemd=false \
    -Dalsa=true \
    -Dcolord=false \
    -Dcups=false \
    -Dnetwork_manager=false \
    -Dsmartcard=false \
    -Dwacom=false \
    -Dwayland=false \
    -Dwwan=false \
    . output

ninja -C output
ninja -C output install
