#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dalsa=true \
    -Dsystemd=false \
    -Dwwan=false \
    -Dwayland=false \
    -Dwacom=false \
    -Dsmartcard=false \
    -Dnetwork_manager=false \
    . output

ninja -C output
ninja -C output install
