#!/bin/sh -e

autoreconf -fi

sed -i 's/diff -c/diff/g' telepathy-glib/abi.am telepathy-glib/Makefile.in

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-vala-keybindings

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/gtk-doc"
