#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

meson \
    --prefix=/usr \
    --buildtype=plain \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/lib/gobject-introspection/giscanner/doctemplates"
rm -rf "$1/usr/share/gobject-introspection-1.0/tests"
rm -rf "$1/usr/share/man"
