#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=None \
    -DWITH_ASF=ON \
    -DWITH_MP4=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_TESTS=OFF

cmake --build   build
cmake --install build
