#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

cd AppStream-0.12.11

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=plain \
    -Dqt=false \
    -Dmaintainer=false \
    -Ddocs=false \
    -Dapidocs=false \
    -Dinstall-docs=false \
    -Dstemming=false \
    -Dvapi=false \
    -Dapt-support=false \
    -Dgir=true \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/share/gettext"
rm -rf "$1/usr/share/man"
