#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

sed -i 's/xml_i18n = //g' data/profiles/meson.build

meson \
    --prefix=/usr \
    --buildtype=plain \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dsystemd=false \
    -Dargyllcms_sensor=false \
    -Dman=false \
    -Ddocs=false \
    -Ddaemon_user=colord \
    -Dsane=false \
    -Dvapi=true \
    -Dbash_completion=false \
    -Dtests=false \
    output .

ninja -C output
ninja -C output install
