#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < icu-68.patch

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DSHARED_ONLY=true \
    -DENABLE_GTK_DOC=false \
    -DGOBJECT_INTROSPECTION=true \
    -DICAL_GLIB_VAPI=true

cmake --build   build
cmake --install build
