#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-build.patch

rm -rf help
sed -i "/'help'/d" meson.build

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib/epiphany \
    -Ddeveloper_mode=false \
    -Dnetwork_tests=disabled \
    -Dtech_preview=false \
    -Dunit_tests=disabled \
    . output

ninja -C output
ninja -C output install
