#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 -i "$patch"
done

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib/vte \
    --sysconfdir=/etc \
    --buildtype=plain \
    -Ddocs=false \
    -D_systemd=false \
    . output

ninja -C output
ninja -C output install
