#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

sed -i -e "/'test-.*'/d" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dgnome_distributor="KISSLinux" \
    -Dudev=enabled \
    -Dinstalled_tests=false \
    -Dgtk_doc=false \
    -Ddesktop_docs=false \
    . output

ninja -C output
ninja -C output install
