#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --enable-static \
    --localstatedir=/var

make
make DESTDIR="$1" install

# Remove man files
rm -rf "${1:?}/usr/share"
