#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dgtk_doc=false \
    . output

ninja -C output
ninja -C output install
