#!/bin/sh -e

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-static

make
make DESTDIR="$1" install
