#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -Np1 -i "$patch"
done

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install

# Remove unused stuff
rm -rf "$1/usr/share/applications/gala-wayland.desktop"
