#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=plain \
    -Dtests=false \
    -Dintrospection=enabled \
    -Ddocbook_docs=disabled \
    -Dgtk_doc=false \
    -Dman=false \
    . output

ninja -C output
ninja -C output install
