#!/bin/sh -e

name=lightdm

addgroup -S "$name" 2>/dev/null
adduser -S -D -H -h /var/lib/lightdm -s /bin/false -G "$name" -g "$name" "$name" 2>/dev/null

chown lightdm:lightdm /var/lib/lightdm
chown lightdm:lightdm /var/lib/lightdm-data

exit 0
