#!/bin/sh -e

export DESTDIR="$1"

# Invalid vala syntax, new release will solve this
sed -i 's/Variant\[2\] t/Variant\[\] t/g' src/Views/LocationPanel.vala

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
