#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_C_FLAGS_MINSIZEREL="$CFLAGS" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_DOCUMENTATION=False

cmake --build   build
cmake --install build
